import { Request, Response } from 'express';
import { AppDataSource } from '../config/data-source.js';
import { AiGeneration } from '../entities/AiGeneration.js';
import { MoreThanOrEqual } from 'typeorm';
import path from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const UPLOAD_DIR = path.join(__dirname, '..', '..', 'uploads', 'studio');

const WORKER_URL = 'https://lingering-disk-82c5.thaidt15.workers.dev';
const DAILY_LIMIT = 3;

// Ensure upload directory exists
fs.mkdirSync(UPLOAD_DIR, { recursive: true });

function getStartOfDay(): Date {
    const now = new Date();
    now.setHours(0, 0, 0, 0);
    return now;
}

// GET /api/ai/usage — current user's daily usage
export const getUsage = async (req: Request, res: Response) => {
    try {
        const userId = (req as any).user.id;
        const repo = AppDataSource.getRepository(AiGeneration);
        const used = await repo.count({
            where: { user_id: userId, created_at: MoreThanOrEqual(getStartOfDay()) }
        });
        res.json({ used, limit: DAILY_LIMIT, remaining: Math.max(0, DAILY_LIMIT - used) });
    } catch (err) {
        console.error('Error fetching AI usage:', err);
        res.status(500).json({ message: 'Không thể lấy thông tin sử dụng AI' });
    }
};

// GET /api/ai/history — all AI images generated by the current user
export const getHistory = async (req: Request, res: Response) => {
    try {
        const userId = (req as any).user.id;
        const repo = AppDataSource.getRepository(AiGeneration);
        const records = await repo.find({
            where: { user_id: userId },
            order: { created_at: 'DESC' },
            select: ['id', 'image_url', 'prompt', 'created_at'],
        });
        res.json(records.map(r => r.image_url));
    } catch (err) {
        console.error('Error fetching AI history:', err);
        res.status(500).json({ message: 'Không thể lấy lịch sử AI' });
    }
};

// POST /api/ai/generate — generate image via Worker, save it, track usage
export const generateImage = async (req: Request, res: Response) => {
    try {
        const userId = (req as any).user.id;
        const { prompt } = req.body;

        if (!prompt || typeof prompt !== 'string' || prompt.trim().length === 0) {
            return res.status(400).json({ message: 'Prompt không được để trống' });
        }

        // Check daily limit
        const repo = AppDataSource.getRepository(AiGeneration);
        const used = await repo.count({
            where: { user_id: userId, created_at: MoreThanOrEqual(getStartOfDay()) }
        });

        if (used >= DAILY_LIMIT) {
            return res.status(429).json({
                message: `Bạn đã sử dụng hết ${DAILY_LIMIT} lượt tạo ảnh AI hôm nay. Vui lòng thử lại vào ngày mai.`,
                used,
                limit: DAILY_LIMIT,
            });
        }

        // Call Worker API
        const workerRes = await fetch(WORKER_URL + '/generate', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ prompt: prompt.trim() }),
        });

        if (!workerRes.ok) {
            const errText = await workerRes.text();
            console.error('Worker generate error:', workerRes.status, errText);
            return res.status(502).json({ message: 'AI Worker trả về lỗi. Vui lòng thử lại.' });
        }

        // Save image blob to disk (in user-specific folder)
        const blob = await workerRes.arrayBuffer();
        const userDir = path.join(UPLOAD_DIR, userId);
        fs.mkdirSync(userDir, { recursive: true });
        const filename = `ai-${Date.now()}-${Math.random().toString(36).substring(2, 8)}.png`;
        const filePath = path.join(userDir, filename);
        fs.writeFileSync(filePath, Buffer.from(blob));

        const imageUrl = `/uploads/studio/${userId}/${filename}`;

        // Record the generation
        const record = repo.create({ user_id: userId, prompt: prompt.trim(), image_url: imageUrl });
        await repo.save(record);

        res.json({
            url: imageUrl,
            used: used + 1,
            limit: DAILY_LIMIT,
            remaining: Math.max(0, DAILY_LIMIT - used - 1),
        });
    } catch (err) {
        console.error('Error generating AI image:', err);
        res.status(500).json({ message: 'Không thể tạo ảnh AI. Vui lòng thử lại.' });
    }
};

const CF_ACCOUNT_ID = process.env.CF_ACCOUNT_ID || '';
const CF_API_TOKEN = process.env.CF_API_TOKEN || '';

// POST /api/ai/review — call Cloudflare AI directly for design review
export const reviewImage = async (req: Request, res: Response) => {
    try {
        if (!req.file) {
            return res.status(400).json({ message: 'Vui lòng chọn ảnh để review' });
        }

        if (!CF_ACCOUNT_ID || !CF_API_TOKEN) {
            return res.status(500).json({ message: 'Chưa cấu hình CF_ACCOUNT_ID / CF_API_TOKEN' });
        }

        const fileBuffer = fs.readFileSync(req.file.path);
        const base64 = fileBuffer.toString('base64');
        const mimeType = req.file.mimetype || 'image/jpeg';
        console.log('[Review] Image size:', fileBuffer.length, 'bytes');

        // Clean up temp file
        try { fs.unlinkSync(req.file.path); } catch { }

        // Call Cloudflare AI REST API directly with multimodal content format
        const aiRes = await fetch(
            `https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/ai/run/@cf/meta/llama-3.2-11b-vision-instruct`,
            {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${CF_API_TOKEN}`,
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    messages: [
                        {
                            role: 'system',
                            content: 'Bạn là chuyên gia thiết kế thời trang cực kỳ nhiệt tình và luôn nhìn ra những điểm tuyệt vời trong mọi tác phẩm. Hãy dùng những từ ngữ hoa mỹ, tích cực nhất để khen ngợi người dùng. Luôn trả lời bằng tiếng Việt. Dùng nhiều emoji để tạo không khí vui vẻ, khích lệ. 🌟✨'
                        },
                        {
                            role: 'user',
                            content: [
                                { type: 'text', text: 'Hãy nhận xét thiết kế áo này một cách cực kỳ tích cực và hào hứng! Hãy khen ngợi những điểm ấn tượng nhất (bố cục, sự phối màu sáng tạo, ý tưởng vượt bậc). Sau đó đưa 1-2 gợi ý nhỏ xíu để làm nó còn hoàn hảo hơn nữa. Hãy làm cho người dùng cảm thấy tự hào về thiết kế của họ! Trả lời bằng tiếng Việt, 3-5 câu. 🚀🎨' },
                                { type: 'image_url', image_url: { url: `data:${mimeType};base64,${base64}` } }
                            ]
                        }
                    ],
                    max_tokens: 512,
                }),
            }
        );

        const data = await aiRes.json() as any;
        console.log('[Review] CF AI status:', aiRes.status, 'result:', JSON.stringify(data).substring(0, 500));

        if (data?.result?.response) {
            return res.json({ result: data.result.response });
        }

        // Fallback: try flat image field format
        if (!data?.result?.response) {
            console.log('[Review] Trying flat image format...');
            const imageBytes = Array.from(fileBuffer);
            const aiRes2 = await fetch(
                `https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/ai/run/@cf/meta/llama-3.2-11b-vision-instruct`,
                {
                    method: 'POST',
                    headers: {
                        'Authorization': `Bearer ${CF_API_TOKEN}`,
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        messages: [
                            { role: 'system', content: 'Bạn là chuyên gia thiết kế thời trang cực kỳ nhiệt tình và luôn nhìn ra những điểm tuyệt vời. Hãy dùng những từ ngữ tích cực nhất để khen ngợi người dùng. Luôn trả lời bằng tiếng Việt. Dùng nhiều emoji vui vẻ. 🌟' },
                            { role: 'user', content: 'Hãy nhận xét thiết kế áo này một cách hào hứng! Khen ngợi những điểm ấn tượng nhất. Sau đó đưa 1-2 gợi ý nhỏ xíu để hoàn thiện thêm. Làm người dùng cảm thấy tự hào về tác phẩm của mình! Trả lời bằng tiếng Việt, 3-5 câu. 🎨' }
                        ],
                        image: imageBytes,
                        max_tokens: 512,
                    }),
                }
            );
            const data2 = await aiRes2.json() as any;
            console.log('[Review] Flat format result:', JSON.stringify(data2).substring(0, 500));
            if (data2?.result?.response) {
                return res.json({ result: data2.result.response });
            }
        }

        return res.status(502).json({ message: 'AI không trả về nhận xét', detail: data });
    } catch (err) {
        console.error('Error reviewing image:', err);
        res.status(500).json({ message: 'Không thể review ảnh: ' + (err as Error).message });
    }
};

// POST /api/ai/safety — use vision model to check for NSFW content
export const safetyCheck = async (req: Request, res: Response) => {
    try {
        if (!req.file) {
            return res.status(400).json({ message: 'Vui lòng chọn ảnh để kiểm tra' });
        }

        if (!CF_ACCOUNT_ID || !CF_API_TOKEN) {
            return res.json({ unsafe: false, raw: 'CF credentials not configured' });
        }

        const fileBuffer = fs.readFileSync(req.file.path);
        const base64 = fileBuffer.toString('base64');
        const mimeType = req.file.mimetype || 'image/jpeg';
        console.log('[Safety] Image size:', fileBuffer.length, 'bytes');

        // Clean up temp file
        try { fs.unlinkSync(req.file.path); } catch { }

        // Use high-strictness Vision model for all-in-one safety check
        const aiRes = await fetch(
            `https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/ai/run/@cf/meta/llama-3.2-11b-vision-instruct`,
            {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${CF_API_TOKEN}`,
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    messages: [
                        {
                            role: 'system',
                            content: 'You are a strict content moderator for a commercial printing business. You MUST block any image that is inappropriate, offensive, or controversial.'
                        },
                        {
                            role: 'user',
                            content: [
                                {
                                    type: 'text',
                                    text: 'Analyze this image. Does it contain any of the following: 1. Nudity or sexual content. 2. Violence or gore. 3. Controversial political symbols, protest signs, or sensitive social movements (e.g., BLM, political rallies). 4. Offensive/hate speech. If ANY of these are present, respond ONLY "unsafe". Otherwise respond "safe".'
                                },
                                { type: 'image_url', image_url: { url: `data:${mimeType};base64,${base64}` } }
                            ]
                        }
                    ],
                    max_tokens: 10,
                }),
            }
        );

        const data = await aiRes.json() as any;
        console.log('[Safety] CF Response:', JSON.stringify(data));
        const text = (data?.result?.response || '').trim().toLowerCase();

        console.log('[Safety] Extracted text:', text);
        // Block if it says unsafe OR doesn't clearly say safe
        const isUnsafe = text.includes('unsafe') || text.includes('violation') || text.includes('no') || !text.includes('safe');

        console.log('[Safety] Final result:', { text, isUnsafe });
        res.json({ unsafe: isUnsafe, raw: text });
    } catch (err) {
        console.error('Error safety checking image:', err);
        res.json({ unsafe: false, raw: 'error' });
    }
};
